name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: 'Login to GitHub Container Registry'
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}
    - name: Build the Docker image
      run: |
        docker build . --file containerfile --tag ghcr.io/dionmm/django-basic:$(date +%M%H%j)
        docker push ghcr.io/dionmm/django-basic:$(date +%M%H%j)
